### ISSUE TITLE
How to show form validation errors?

### ISSUE THREAD

**Issue by Tropicalista** [elpete/cbInertia#2]
How can I show the form validation errors?

**Comment by elpete** [comment]
Here's one example:

https://github.com/elpete/quick-tailwind-inertia/blob/8d3627f39254c32817d1d42e720cba05eba80d3b/interceptors/SharedInertiaDataInterceptor.cfc#L17-L19

https://github.com/elpete/quick-tailwind-inertia/blob/8d3627f39254c32817d1d42e720cba05eba80d3b/handlers/Registrations.cfc#L24-L28
